### ISSUE TITLE
ping6 does not support -F flowlabel option

### ISSUE THREAD

**Issue by amitcohen1** [iputils/iputils#268]
I use Fedora31 and ping6 failed with the following error:
$ ping6 2001:db8:2::2 -F 0 -c 1 -q
ping6: flow labels are not supported

The same command, just without -F option works well.
$ ping6 2001:db8:2::2 -c 1 -q
--- 2001:db8:2::2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.116/0.116/0.116/0.000 ms
PING 2001:db8:2::2(2001:db8:2::2) 56 data bytes

flowable option works well in iputils-20180629-4 and it's broken in iputils-20190515-5.

**Comment by kerolasa** [comment]
Hi @amitcohen1 I just made a pull request  https://github.com/iputils/iputils/pull/270 that should address the issue. Let see what other people who watch this project have to say about the change, as it has open question of why the headers are behaving so strange way.

**Comment by kerolasa** [comment]
The issue should be fixed, see 60c28a5865b7dcc41946bff7e8ed173bf712c0d1. Thank you for bug report @amitcohen1

**Comment by amitcohen1** [comment]
Thanks!

**Comment by amitcohen1** [comment]
Hi, trying to check the fix and it seems that the issue is still occurs.
I installed iputils from master using - "./configure && make && make install".
$ which arping
/usr/local/bin/arping

The same error is shown:
$ ping6 2001:db8:2::2 -F 0 -c 1 -q
ping6: flow labels are not supported

Did I miss something?

**Comment by pevik** [comment]
I tested it only on `::1`, works for me (and verify that without fix it's not working). Can you check that (+ check version)?
```
$ ./builddir/ping/ping -6 ::1 -F 0 -c 1 -q
PING ::1(::1) , flow 0xf78bb, 56 data bytes

--- ::1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.066/0.066/0.066/0.000 ms

$ ./builddir/ping/ping -V
ping from iputils s20190709-96-g60c28a5
```

**Comment by amitcohen1** [comment]
Can I declare the default "ping6" to be ./builddir/ping/ping -6?
I want to use it as part of kernel tests without changing the tests.

**Comment by pevik** [comment]
Either use `ping -6` or symlink ping to be `ping6` (equal functionality).

BTW are you using LTP network tests?
https://github.com/linux-test-project/ltp/tree/master/testcases/network

**Comment by amitcohen1** [comment]
no, I'm running kernel selftests.
Now it works, thanks!
