### ISSUE TITLE
Clockdiff host is down

### ISSUE THREAD

**Issue by LurenAA** [iputils/iputils#326]
I have two computers，in a Campus Network.  they can ping each other. I can use ssh to connect one using the other one. but when I use clockdiff , both show "host is down". is there any thing wrong ? thanks 

ubuntu 20.04
5.4.0-42-generic
![image](https://user-images.githubusercontent.com/45759613/115235231-8bcd3500-a14c-11eb-8493-39f94dcc3bc8.png)

**Comment by JokerShao** [comment]
same problem.

**Comment by JokerShao** [comment]
but i can get right result use clockdiff from apt repository

**Comment by pevik** [comment]
Can you please reproduce the problem on publicly visible hosts? That'd be much easier to reproduce for us. 

Can you test it on current master and then try to bisect if older version works?

if problem found on `clockdiff` in package which version and distro you use? Never versions (>= `s20190324`) support print version (`clockdiff -V`, for other versions we rely on distro package info.

@LurenAA Also please next time copy paste output. Github allows code formatting with `< >` button and text can be further copied.

**Comment by JokerShao** [comment]
1. sorry, i can't reproduce the problem on publicly visible hosts, many router will ignore the ip and icmp timestamp;
    ```
    In my case, i have a dual network card laptop, one is ethernet(192.168.10.0/24), another is wireless networkcard(128.1.0.0/24).
    on ethernet card, it work well, but not work on wifi, echo is host down.
    ```
2. i have test the release version from 20210202 to 20180629, they're not work;
3. i don't known which version in apt repository, but i downloaded a version from `http://www.skbuff.net/iputils/`, iputils-s20151218.tar.bz2, it works well.

**Comment by 6eh01der** [comment]
@LurenAA I suppose that ICMP type 13 is blocked on target machine. Try to disable ufw. ICMP type 13 -  ICMP Timestamp. It used by default in clockdiff. Also you could add option -o and clockdiff will send ICMP ECHO packets with IP TIMESTAMP option instead of ICMP Timestamp packets. Successfully tested on Ubuntu 20.04.
@JokerShao Maybe apt version use -o option by default.

**Comment by yueryoufeng** [comment]
@6eh01der Thank you for your reply.
@pevik  @kerolasa  The changed commit is https://github.com/iputils/iputils/commit/acb7fbbc48c368551d2f2da7d446d12ad7e1e172
Probably 323-327

**Comment by themoses** [comment]
@pevik I sent you a mail containing the details. Thanks for pinging me

**Comment by pevik** [comment]
@LurenAA It should be fixed, if not, please let us know.

**Comment by eaglegai** [comment]
@pevik i'm sorry to say 913939743b7 didn't fix #326 #374 ,maybe we still need aa969df2b when the network  situation is not very well

**Comment by eaglegai** [comment]
after patch 913939743b7, ‘’xxx is down‘ will still happen by chance
[root@localhost SPECS]# clockdiff 99.99.100.3
............................clockdiff: 99.99.100.3 is down
[root@localhost SPECS]# ping -c 3 99.99.100.3
PING 99.99.100.3 (99.99.100.3) 56(84) bytes of data.
64 bytes from 99.99.100.3: icmp_seq=1 ttl=64 time=0.474 ms
64 bytes from 99.99.100.3: icmp_seq=2 ttl=64 time=0.439 ms
64 bytes from 99.99.100.3: icmp_seq=3 ttl=64 time=0.427 ms

--- 99.99.100.3 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2028ms
rtt min/avg/max/mdev = 0.427/0.446/0.474/0.019 ms
[root@localhost SPECS]# clockdiff 99.99.100.3
...........................clockdiff: 99.99.100.3 is down
[root@localhost SPECS]# clockdiff 99.99.100.3
...........................clockdiff: 99.99.100.3 is down
[root@localhost SPECS]# clockdiff 99.99.100.3
...........................clockdiff: 99.99.100.3 is down
[root@localhost SPECS]# clockdiff 99.99.100.3
...........................clockdiff: 99.99.100.3 is down
[root@localhost SPECS]# clockdiff 99.99.100.3
............................clockdiff: 99.99.100.3 is down
[root@localhost SPECS]# clockdiff 99.99.100.3
..................................................
host=99.99.100.3 rtt=2(1)ms/1ms delta=-24141ms/-24140ms Wed Jan  4 10:56:40 2023
[root@localhost SPECS]# clockdiff 99.99.100.3
..................................................
host=99.99.100.3 rtt=3(0)ms/2ms delta=-24140ms/-24140ms Wed Jan  4 10:56:48 2023
[root@localhost SPECS]# clockdiff 99.99.100.3
...................................................
host=99.99.100.3 rtt=3(0)ms/2ms delta=-24140ms/-24140ms Wed Jan  4 10:56:56 2023
[root@localhost SPECS]#

**Comment by 6eh01der** [comment]
Absolutly right, [9139397](https://github.com/iputils/iputils/commit/913939743b7b0893eae80792548574a197523720) fixes only #422 and it has nothing to do with #374 and #326. Maybe #380 could fix mentioned problems (it containes [aa969df](https://github.com/iputils/iputils/commit/aa969df2be0fb494f405e98152c29ad985d543e3).

**Comment by eaglegai** [comment]
hi ，is there any things new about this issue?

**Comment by pevik** [comment]
Well, as @nmeyerhans mentioned in https://github.com/iputils/iputils/pull/459#issuecomment-1536605414 we should try https://github.com/iputils/iputils/pull/459#issuecomment-1536605414 and https://github.com/iputils/iputils/pull/459. 

@eaglegai Could you please try both of them, if they fix your problem?

**Comment by eaglegai** [comment]
> Well, as @nmeyerhans mentioned in [#459 (comment)](https://github.com/iputils/iputils/pull/459#issuecomment-1536605414) we should try [#459 (comment)](https://github.com/iputils/iputils/pull/459#issuecomment-1536605414) and #459.
> 
> @eaglegai Could you please try both of them, if they fix your problem?

no problems, but you mean the both are  #459 and #380 ？

**Comment by eaglegai** [comment]
I try clockdiff 100 times.
patch nothing:   "xxx is down"  appeared 28 times
patch #459 :  "xxx is down"  appeared 0 times
patch #380 :  "xxx is down"  appeared 0 times

@pevik  both of them can fix it.

**Comment by pevik** [comment]
@nmeyerhans I prefer https://github.com/iputils/iputils/pull/459, WDYT?

**Comment by yueryoufeng** [comment]
> @nmeyerhans我更喜欢#459，WDYT？

I think so.

**Comment by nmeyerhans** [comment]
@pevik Yes, I'm inclined to prefer #459 as well.

**Comment by pevik** [comment]
Finally fixed, I'm sorry it took so long.
